### PR TITLE
Fixed some conversion errors that occur when the -Wc++-compat compiler flag is enabled

### PR DESCRIPTION
**Pull request by NoelGraf**
The compiler flag -Wc++-compat causes some errors in the build process. These are conversion errors that I fixed in this PR.
Attached is a [build.log](https://github.com/LiamBindle/MQTT-C/files/8464601/build.log).

We are using the MQTT library in the open-source project open62541. For this reason, it would be great if the PR is merged as soon as possible. Also, it would be great if a new tag could be created after the merge, which we can then use for our git submodules.
Thanks

### CODE REVIEW

**Comment by NoelGraf** [comment]
Hello @LiamBindle,
First-time contributors need a maintainer to approve running workflows. 
Can you approve the running workflows and take a look at my PR?

**Comment by LiamBindle** [comment]
@NoelGraf Thanks for the contribution! Sorry for the slow response. My GitHub notifications are out of control.

I don't forsee any issues with this update. I'd just like to review that the casts are all to appropriate types. I'll try to get to it this weekend.

**Comment by NoelGraf** [comment]
Many Thanks!

**Comment by NoelGraf** [comment]
Hi @LiamBindle,
is there anything I can help you with to merge the PR?

**Comment by andreasebner** [comment]
Hi @LiamBindle, it would be realy cool if we can change to the upstream repository in our open62541 repository. Can you give us an short status update on the merge process?

**Comment by LiamBindle** [comment]
Done! Release v1.1.6. Sorry for the slow response.

**Pull request merged**
