### PR TITLE
Issue/90 MQTT-C header rename

### PR DESCRIPTION
**Pull request by vpetrigo**
Rename:
 - `mqtt.c` -> `mqttc.c`
 - `mqtt.h` -> `mqttc.h`

Update:
 - CMake and Makefile to use renamed MQTT-C source file
 - examples and tests to use renamed MQTT-C header file

### CODE REVIEW

**Comment by LiamBindle** [comment]
@vpetrigo Thanks for this. Could you change `mqtt_pal.c` -> `mqttc_pal.c` and `mqtt_pal.h` -> `mqttc_pal.h`  too?

**Comment by vpetrigo** [comment]
Should be done. 😄

**Comment by yamt** [comment]
what's the motivation of the rename?

**Comment by yamt** [comment]
answering myself, there's an issue with the explanation. https://github.com/LiamBindle/MQTT-C/issues/90

**Comment by LiamBindle** [comment]
@vpetrigo Just following up on this. I'll merge this when I have a chance to revise some of the documentation. It might be a little while, but this will get merged. Thanks for your patience.

**Comment by vpetrigo** [comment]
@LiamBindle just FYI there were some merge conflicts that I just resolved.

**Comment by vpetrigo** [comment]
Hey @LiamBindle, would you tell if you have timeline in mind when this PR will be merged? 😄 I just realised that there another bunch of conflicts and I'm wondering whether I should them resolve now.

**Comment by LiamBindle** [comment]
@vpetrigo I apologise for the slow response. 

The issue I'm running into is these changes break compatability and therefore warrant a major version upgrade (i.e., if someone does `git pull` it will break their project, t.f., this would need to go into a version 2.0). But I don't think renaming files is a substantial enough upgrade to warrant a major version release. 

I haven't heard other requests for this, and it could alternatively be solved by contraining your include directories, so I'm hesitant to merge this. What do you think?

Perhaps, @learn-more @jepaan @yamt @markrad, do you have any thoughts on whether `mqtt.c` should be renamed to `mqttc.c`?

**Comment by vpetrigo** [comment]
@LiamBindle, I may suggest bundling a `mqtt.h` that will include renamed `mqttc.h`. That file may be deleted later in `v2.0+` for example when people most likely move to a `mqttc.h` header file.

**Comment by learn-more** [comment]
I have no strong preference about the naming, but if you want to prevent naming conflicts a header structure like <mqttc/mqttc.h> seems even more distinct.

the mqtt.h in-between header seems like a nice touch, you could generate a warning in that before including the real header,
but that does not solve the conflicting header issue right now?

**Comment by vpetrigo** [comment]
If we put renamed `mqttc.h` into a subfolder in the `include/` directory – it will solve.

**Comment by yamt** [comment]
the compat mqtt.h would make my life as a consumer of this library a bit easier.

**Comment by LiamBindle** [comment]
The `mqtt.h` compatability file would cause the same error this PR is intended to fix though. 

This issue only affects a small portion of users, and the fix would break compability for a much larger portion of users. Additionally, for any users that are affected by conflicting header file names, they could simply restrict their include directories or rename the file.

Since there isn't substantial support for this and it would break compatibility for a larger user group than it would help, I'm going to close this PR. I hope you understand. I'm happy to discuss further if you would like. Hope to see more PRs in the future!

it is relatively easily fixable, and the fix would break compatibility, I'm going to close this PR.

**Comment by vpetrigo** [comment]
So, do you mind me making the following changes:
- move `mqttc.h` and `mqttc_pal.h` into the `mqttc/` subfolder under the `include/` dir
- provide a `mqtt.h` and `mqtt_pal.h` with the following code:
```c
// mqtt.h
#ifndef __MQTT_GUARD__
#define __MQTT_GUARD__

#include "mqttc/mqttc.h"
#warning "This file might be deprecated in the upcoming versions"

#endif /* __MQTT_GUARD __ */

// mqtt.h
#ifndef __MQTT_PAL_GUARD__
#define __MQTT_PAL_GUARD__

#include "mqttc/mqttc_pal.h"
#warning "This file might be deprecated in the upcoming versions"

#endif /* __MQTT_PAL_GUARD__ */
```

?

That help me as a user of that library to specify `include/mqttc` as a root include directory for the project, so that it resolves the issue for my case and will not break existing code.

**Comment by LiamBindle** [comment]
I'd suggest doing this your fork. Alternatively you could create a new directory `mqttc/` and symlink `../src` and `../include` and that would fix your problem too. 

MQTT-C is stable, so this would be easy to maintain moving forward. In terms of the real file structure, I would like to keep it as is.

**Comment by vpetrigo** [comment]
Got it, Liam. Thank you for your patience. 😄

**Comment by LiamBindle** [comment]
No problem! Thanks for your contributions to MQTT-C :smile: I hope you'll continue to submit PRs!

**Comment by markrad** [comment]
Late to the party but I am inclined to agree with Liam on this. I looked at the lwip referenced in the original issue and, from my perspective, the issue should be posted on their repo not this one. They have crammed the headers for multiple protocols into a single directory meaning if you want to use their http for example you get stuck with mqtt.h in your search path too. I think it is perfectly reasonable for an app that is solely an MQTT client to have a header called mqtt.h. This only is a problem because of the armmbed header layout.

**Pull request closed without merging**
