### PR TITLE
Enable NuttX(https://github.com/apache/incubator-nuttx) support

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by LiamBindle** [comment]
Thanks @xiaoxiang781216

**Comment by xiaoxiang781216** [comment]
@LiamBindle when will you announce the next offical release? so we can update our build script to download the new package.

**Comment by LiamBindle** [comment]
@xiaoxiang781216 I just released 1.1.5. Hope that helps.

One question relevant to NuttX: Do you have any concerns about us switching the mutex in the UNIX/APPLE/NUTTX PAL to a recursive mutex? https://github.com/LiamBindle/MQTT-C/pull/128#discussion_r591595612

**Comment by xiaoxiang781216** [comment]
No, problem. since NuttX suppor the recursive mutex too:
https://github.com/apache/incubator-nuttx/blob/master/include/pthread.h#L101-L104

**Pull request merged**
