### PR TITLE
Create explicit functions for each PAL protocol

### PR DESCRIPTION
**Pull request by maht**
This will allow easy support of socket handles that support several transports at runtime. For example able to establish two connections over TLS and TCP transport without recompiling.

### CODE REVIEW

**Review by lulingar — APPROVED** [review]

**Comment by yamt** [comment]
@lulingar have you approved this version of the PR intentionally?

**Comment by lulingar** [comment]
@yamt I have probably misfired this, when approving a related PR.

**Comment by lulingar** [comment]
@LiamBindle can you consider this PR please?

**Comment by LiamBindle** [comment]
Hi @maht, thanks for submitting this. Sounds like a great idea. Sorry about the delayed response.

Could you expand on how this works? I don't understand how this allows one to switch the socket type at runtime. Since the `mqtt_pal_recvall()` called in `__mqtt_recv()` is the function defined by `mqtt_pal_recvall`, doesn't it still only support one type?

**Comment by yamt** [comment]
> Hi @maht, thanks for submitting this. Sounds like a great idea. Sorry for the delayed response.
> 
> Could you expand on how this works? I don't understand how this allows one to switch the socket type at runtime. Since the `mqtt_pal_recvall()` called in `__mqtt_recv()` is the function defined by `mqtt_pal_recvall`, doesn't it still only support one type?

the basic idea is to allow building multiple backends (with different names) so that a user can use them to build his custom thin pal which simply dispatches operations to one of those backends.

**Comment by LiamBindle** [comment]
I see, thanks for the clarification. I think this could be accomplished by writing a new custom PAL for the combination of transports that you want to use. Then you could use the `mqtt_client::reconnect_state` to store any context info you need at run time. Perhaps this is what you suggested, just you wouldn't have to copy-paste sections of the default PAL list to your new PAL. 

If that's the case, I would prefer to keep the PAL layer as is. I think we should value simplicity in the PAL---the PAL is meant to be extended not ready-built.

Thanks for the contribution but respectfully I think I will decline merging this in. I think it's a good idea, just not something that should go in the official version. Please feel free to reopen if I've misunderstood anything or if you want to discuss it further.

**Comment by maht** [comment]
@LiamBindle Sorry for the delayed response too, it caught me just before my holidays and I forgot to answer after them. Simplicity is a good asset, so I understand maybe is better not to merge if it can be implemented in another way. Thanks for your review.

**Pull request closed without merging**
