### PR TITLE
Issue/91 Unaligned TX buffer docs

### PR DESCRIPTION
**Pull request by vpetrigo**
Add:
 - attention block with unaligned `sendbuf` issue description (#91)

Update:
 - `README.md` to avoid `autotoc_md0` generation due to empty `#` statement
 - `docs/` output

### CODE REVIEW

**Comment by LiamBindle** [comment]
@vpetrigo Thanks for the update. I have some other updates to the docs that I need to make, so I'm going to do these all at the same time. It might take me a week or so to get to this however. Thanks for this!

**Comment by LiamBindle** [comment]
@vpetrigo Just following up on this. I'm going to merge this along with some other updates to documentation in a little while. This will get merged. Thanks for your patience.

**Comment by LiamBindle** [comment]
@vpetrigo Could you remove a37bc2b. I have some other updates to the Doxygen files, so I need to regenerate it all anyways and I'd like to minimize the diff. I'll merge immediately one a37bc2b is removed.

**Comment by vpetrigo** [comment]
@LiamBindle, I made changes you asked.

**Comment by LiamBindle** [comment]
Thanks @vpetrigo!

**Pull request merged**
