### PR TITLE
Make mqtt_pal empty is case of MQTT_USE_CUSTOM_SOCKET_HANDLE

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by LiamBindle** [comment]
Thanks @yamt! This is a good idea. I'll take a look at this this week---I see there's a rogue `#ifdef` in the PAL (not from this PR) that I'd like to replace at the same time.

**Comment by yamt** [comment]
> Thanks @yamt! This is a good idea. I'll take a look at this this week---I see there's a rogue `#ifdef` in the PAL (not from this PR) that I'd like to replace at the same time.

can you explain "a rogue #ifdef" a bit?
at a glance, i haven't noticed anything wrong in this file.

**Comment by LiamBindle** [comment]
[Here](https://github.com/LiamBindle/MQTT-C/blob/12f9fa853dacdf82fdf555274670d22239e4abce/src/mqtt_pal.c#L47) it's an `#ifdef` where everywhere else is using `#if defined()`. I'd like to review that file and make sure everything is consistent.

**Comment by yamt** [comment]
> [Here](https://github.com/LiamBindle/MQTT-C/blob/12f9fa853dacdf82fdf555274670d22239e4abce/src/mqtt_pal.c#L47) it's an `#ifdef` where everywhere else is using `#if defined()`. I'd like to review that file and make sure everything is consistent.

do you mean to make a change like this? https://github.com/LiamBindle/MQTT-C/pull/142

**Comment by LiamBindle** [comment]
Yeah that's what I was thinking. Thanks!

**Pull request merged**
