### PR TITLE
Possible socket leak. send() can return -1 and expect a retry.

### PR DESCRIPTION
**Pull request by przemyslawzygmunt**

### CODE REVIEW

**Comment by LiamBindle** [comment]
Thanks for your contribution @przemyslawzygmunt! Hope to see more PRs in the future!

**Comment by LiamBindle** [comment]
Thanks for the contribution @przemyslawzygmunt! Do you mind fixing the conflict? Sorry, I think this was introduced by me merging #112. Then I'll merge!

**Comment by przemyslawzygmunt** [comment]
PR #112 doesn't solve the problem because of "if (rv == -1) continue;". In this case, the sockfd can be reinitialized without closing the handle

**Comment by LiamBindle** [comment]
It should be this right?

```c
    /* open the first possible socket */
    for(p = servinfo; p != NULL; p = p->ai_next) {
        sockfd = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
        if (sockfd == -1) continue;

        /* connect to server */
        rv = connect(sockfd, p->ai_addr, p->ai_addrlen);
        if(rv == -1) {
          close(sockfd);
          sockfd = -1;
          continue;
        }
        break;
    }  
```

Sorry, it's been a while since I looked a this. Just want to double check I do this right.

**Comment by przemyslawzygmunt** [comment]
Yes it is correct

**Comment by LiamBindle** [comment]
Thanks @przemyslawzygmunt! Hope you'll continue to make PRs!

**Pull request merged**
