### PR TITLE
compile with MINGW64 GCC

### PR DESCRIPTION
**Pull request by kimim**
this PR makes it possible to be compiled with MINGW32/64 GCC
all the tests are passed.

### CODE REVIEW

**Comment by LiamBindle** [comment]
Thanks for the contribution @kimim! It looks good to me. Could you just remove the diffs to trailing whitespace? That will make this PRs diff more readable.

**Comment by kimim** [comment]
Hi @LiamBindle , I've removed additional spaces changes. 
The trailing spaces are automatically removed by emacs, my text editor.

**Comment by LiamBindle** [comment]
@kimim Thanks! This looks good to me. I'm a bit overloaded right now, but I'll merge this when I get a chance.

**Comment by LiamBindle** [comment]
Thanks for the contribution @kimim! Sorry for the slow response.

**Pull request merged**
