### PR TITLE
Minor changes to increase C compliance

### PR DESCRIPTION
**Pull request by jepaan**

### CODE REVIEW

**Comment by jepaan** [comment]
Hi
The third commit with the license added was not supposed to be added. Never used GitHub for this before.
Feel free to reject if you don't want the license added. I can re-request without it.

**Comment by LiamBindle** [comment]
Hi Jepaan,

Sure, I'd be happy to merge these changes. Adding the license to the source files is probably a good idea since most people probably copying the MQTT-C source files into other repositories. We should probably add the license to `mqtt_pal.h` and `mqtt_pal.c` as well though. Could you add the license to those files? 

Liam

**Comment by jepaan** [comment]
Hi Liam

I've added it to the files.

I have another question. Are you interested in having the project being C89 compliant? 
One of the platforms I'm using is "mostly" C89 compliant, and I have the code running with minor modifications. Would you be interested in merge this as well?

**Comment by LiamBindle** [comment]
Hi Jepaan,

Thanks, I'll merge that in!

Yeah, I think that C89 compliance would be probably help some people--it would improve the portability of MQTT-C especially for anyone developing on Windows at the very least. If you submit another merge request I will review the changes.

Thanks for the contribution,

Liam

**Pull request merged**
